apiVersion: v1
kind: Cluster
metadata:
  name: my-cluster
spec:
  clusterNetwork:
    services:
     CIDR: 10.43.0.0/16
    pods:
      cidr: 10.42.0.0/16
  networking:
    serviceSubnet: 10.43.0.0/24
  controlPlaneEndpoint: "127.0.0.1:6443"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default